name: Deploy to Oracle Cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t news-crawler .

    - name: Run Docker container
      run: docker run -d --name news-crawler-temp news-crawler

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.KEY }}
        source: "."
        target: "~/docker/news/"

    - name: Deploy to Oracle Cloud server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/docker/news
          docker stop news-crawler-container || true
          docker rm news-crawler-container || true
          docker build -t news-crawler .
          docker run -d --name news-crawler-container -e SERVER_HOST="${{ secrets.SERVER_HOST }}" -e ABSOLUTE_URL="${{ secrets.ABSOLUTE_URL }}" -e MAIN_URL="${{ secrets.MAIN_URL }}" news-crawler
