name: News CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run Docker container
      run: docker run -d myapp
      
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions - build
        fields: repo,commit,message,author
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() 
    

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.KEY }}
        source: "."
        target: "~/docker/news/"

    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/docker/news
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
          echo "USER_NAME=${{ secrets.SERVER_USERNAME }}" >> .env
          echo "MAIN_URL=${{ secrets.MAIN_URL }}" >> .env
          echo "ABSOLUTE_URL=${{ secrets.ABSOLUTE_URL }}" >> .env
          echo "DOCKER_NAMESPACE=${{ secrets.NAMESPACE }}" >> .env
          echo "PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}" >> .env
          echo "PREFECT_URL=${{ secrets.PREFECT_URL }}" >> .env
          
          docker compose down --rmi all
          docker compose build
          docker compose up -d
          
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions - deploy
        fields: repo,commit,message,author
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
